-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 15:59:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema control
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control` DEFAULT CHARACTER SET utf8 ;
USE `control` ;

-- -----------------------------------------------------
-- Table `control`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`carreras` (
  `idcarreras` INT NOT NULL,
  `nombre` VARCHAR(55) NULL,
  PRIMARY KEY (`idcarreras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`alumnos` (
  `matricula` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `apellidopat` VARCHAR(35) NOT NULL,
  `apellidomat` VARCHAR(35) NOT NULL DEFAULT '',
  `curp` VARCHAR(16) NOT NULL,
  `genero` ENUM('F', 'M') NOT NULL,
  `telfijo` VARCHAR(10) NULL DEFAULT '',
  `cell` VARCHAR(10) NOT NULL DEFAULT '',
  `email` VARCHAR(35) NOT NULL DEFAULT '',
  `fechains` DATE NOT NULL,
  `nss` VARCHAR(15) NULL DEFAULT '',
  `contacto` VARCHAR(100) NULL DEFAULT NULL,
  `status_idstatus` INT(1) NOT NULL,
  `carreras_idcarreras` INT NOT NULL,
  PRIMARY KEY (`matricula`, `carreras_idcarreras`),
  INDEX `fk_alumnos_carreras1_idx` (`carreras_idcarreras` ASC),
  CONSTRAINT `fk_alumnos_carreras1`
    FOREIGN KEY (`carreras_idcarreras`)
    REFERENCES `control`.`carreras` (`idcarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`calificaciones` (
  `parcial` INT(11) NULL DEFAULT NULL,
  `promedio` INT(11) NULL DEFAULT NULL,
  `alumnos_matricula` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`alumnos_matricula`),
  CONSTRAINT `fk_calificaciones_alumnos1`
    FOREIGN KEY (`alumnos_matricula`)
    REFERENCES `control`.`alumnos` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`cicloescolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`cicloescolar` (
  `periodo` VARCHAR(10) NOT NULL,
  `fechain` DATE NULL DEFAULT NULL,
  `fechafin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`maestros` (
  `idcie` VARCHAR(6) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `apellidopat` VARCHAR(35) NOT NULL,
  `apellidomat` VARCHAR(35) NOT NULL,
  `curp` VARCHAR(16) NOT NULL,
  `genero` ENUM('F', 'M') NOT NULL,
  `telfijo` VARCHAR(10) NULL DEFAULT '',
  `cell` VARCHAR(10) NULL DEFAULT '',
  `email` VARCHAR(35) NOT NULL,
  `status` ENUM('ACTIVO', 'COMISION', 'BAJA') NULL DEFAULT NULL,
  PRIMARY KEY (`idcie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`departamentos` (
  `iddepa` INT(11) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL DEFAULT '',
  `maestros_idcie` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`iddepa`, `maestros_idcie`),
  INDEX `fk_departamentos_maestros1_idx` (`maestros_idcie` ASC),
  CONSTRAINT `fk_departamentos_maestros1`
    FOREIGN KEY (`maestros_idcie`)
    REFERENCES `control`.`maestros` (`idcie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`estado` (
  `idedo` INT NOT NULL,
  `nombredo` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idedo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control`.`domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`domicilios` (
  `iddom` INT(11) NOT NULL,
  `calle` VARCHAR(50) NULL DEFAULT '',
  `no` VARCHAR(10) NULL DEFAULT '',
  `colonia` VARCHAR(25) NULL DEFAULT '',
  `codpostal` VARCHAR(5) NULL DEFAULT '',
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`iddom`, `estado_idestado`),
  INDEX `fk_domicilios_estado1_idx` (`estado_idestado` ASC),
  CONSTRAINT `fk_domicilios_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `control`.`estado` (`idedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`materias` (
  `clave` VARCHAR(7) NOT NULL DEFAULT '',
  `nombre` VARCHAR(150) NULL DEFAULT '',
  PRIMARY KEY (`clave`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`grupos` (
  `idclave` INT(11) NOT NULL,
  `materias_clave` VARCHAR(7) NOT NULL,
  `cicloescolar_periodo` VARCHAR(10) NOT NULL,
  `maestros_idcie` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idclave`, `materias_clave`, `cicloescolar_periodo`, `maestros_idcie`),
  INDEX `fk_grupos_materias1_idx` (`materias_clave` ASC),
  INDEX `fk_grupos_cicloescolar1_idx` (`cicloescolar_periodo` ASC),
  INDEX `fk_grupos_maestros1_idx` (`maestros_idcie` ASC),
  CONSTRAINT `fk_grupos_materias1`
    FOREIGN KEY (`materias_clave`)
    REFERENCES `control`.`materias` (`clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_cicloescolar1`
    FOREIGN KEY (`cicloescolar_periodo`)
    REFERENCES `control`.`cicloescolar` (`periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_maestros1`
    FOREIGN KEY (`maestros_idcie`)
    REFERENCES `control`.`maestros` (`idcie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`horarios` (
  `idhorario` INT(11) NOT NULL,
  `horario` VARCHAR(5) NULL DEFAULT NULL,
  `dia` VARCHAR(10) NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`municipio` (
  `idmuni` INT NULL,
  `nomMunicipio` VARCHAR(55) NOT NULL,
  `estado_idedo` INT NOT NULL,
  PRIMARY KEY (`idmuni`, `estado_idedo`),
  INDEX `fk_municipio_estado1_idx` (`estado_idedo` ASC),
  CONSTRAINT `fk_municipio_estado1`
    FOREIGN KEY (`estado_idedo`)
    REFERENCES `control`.`estado` (`idedo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control`.`alumnos_has_domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`alumnos_has_domicilios` (
  `alumnos_matricula` VARCHAR(10) NOT NULL,
  `alumnos_carreras_idcarreras` INT NOT NULL,
  `domicilios_iddom` INT(11) NOT NULL,
  `domicilios_estado_idestado` INT NOT NULL,
  PRIMARY KEY (`alumnos_matricula`, `alumnos_carreras_idcarreras`, `domicilios_iddom`, `domicilios_estado_idestado`),
  INDEX `fk_alumnos_has_domicilios_domicilios1_idx` (`domicilios_iddom` ASC, `domicilios_estado_idestado` ASC),
  INDEX `fk_alumnos_has_domicilios_alumnos1_idx` (`alumnos_matricula` ASC, `alumnos_carreras_idcarreras` ASC),
  CONSTRAINT `fk_alumnos_has_domicilios_alumnos1`
    FOREIGN KEY (`alumnos_matricula` , `alumnos_carreras_idcarreras`)
    REFERENCES `control`.`alumnos` (`matricula` , `carreras_idcarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_domicilios_domicilios1`
    FOREIGN KEY (`domicilios_iddom` , `domicilios_estado_idestado`)
    REFERENCES `control`.`domicilios` (`iddom` , `estado_idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`domicilios_has_maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`domicilios_has_maestros` (
  `domicilios_iddom` INT(11) NOT NULL,
  `domicilios_estado_idestado` INT NOT NULL,
  `maestros_idcie` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`domicilios_iddom`, `domicilios_estado_idestado`, `maestros_idcie`),
  INDEX `fk_domicilios_has_maestros_maestros1_idx` (`maestros_idcie` ASC),
  INDEX `fk_domicilios_has_maestros_domicilios1_idx` (`domicilios_iddom` ASC, `domicilios_estado_idestado` ASC),
  CONSTRAINT `fk_domicilios_has_maestros_domicilios1`
    FOREIGN KEY (`domicilios_iddom` , `domicilios_estado_idestado`)
    REFERENCES `control`.`domicilios` (`iddom` , `estado_idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domicilios_has_maestros_maestros1`
    FOREIGN KEY (`maestros_idcie`)
    REFERENCES `control`.`maestros` (`idcie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`alumnos_has_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`alumnos_has_grupos` (
  `alumnos_matricula` VARCHAR(10) NOT NULL,
  `alumnos_carreras_idcarreras` INT NOT NULL,
  `grupos_idclave` INT(11) NOT NULL,
  `grupos_materias_clave` VARCHAR(7) NOT NULL,
  `grupos_cicloescolar_periodo` VARCHAR(10) NOT NULL,
  `grupos_maestros_idcie` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`alumnos_matricula`, `alumnos_carreras_idcarreras`, `grupos_idclave`, `grupos_materias_clave`, `grupos_cicloescolar_periodo`, `grupos_maestros_idcie`),
  INDEX `fk_alumnos_has_grupos_grupos1_idx` (`grupos_idclave` ASC, `grupos_materias_clave` ASC, `grupos_cicloescolar_periodo` ASC, `grupos_maestros_idcie` ASC),
  INDEX `fk_alumnos_has_grupos_alumnos1_idx` (`alumnos_matricula` ASC, `alumnos_carreras_idcarreras` ASC),
  CONSTRAINT `fk_alumnos_has_grupos_alumnos1`
    FOREIGN KEY (`alumnos_matricula` , `alumnos_carreras_idcarreras`)
    REFERENCES `control`.`alumnos` (`matricula` , `carreras_idcarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_grupos_grupos1`
    FOREIGN KEY (`grupos_idclave` , `grupos_materias_clave` , `grupos_cicloescolar_periodo` , `grupos_maestros_idcie`)
    REFERENCES `control`.`grupos` (`idclave` , `materias_clave` , `cicloescolar_periodo` , `maestros_idcie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control`.`grupos_has_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control`.`grupos_has_horarios` (
  `grupos_idclave` INT(11) NOT NULL,
  `grupos_materias_clave` VARCHAR(7) NOT NULL,
  `grupos_cicloescolar_periodo` VARCHAR(10) NOT NULL,
  `grupos_maestros_idcie` VARCHAR(6) NOT NULL,
  `horarios_idhorario` INT(11) NOT NULL,
  PRIMARY KEY (`grupos_idclave`, `grupos_materias_clave`, `grupos_cicloescolar_periodo`, `grupos_maestros_idcie`, `horarios_idhorario`),
  INDEX `fk_grupos_has_horarios_horarios1_idx` (`horarios_idhorario` ASC),
  INDEX `fk_grupos_has_horarios_grupos1_idx` (`grupos_idclave` ASC, `grupos_materias_clave` ASC, `grupos_cicloescolar_periodo` ASC, `grupos_maestros_idcie` ASC),
  CONSTRAINT `fk_grupos_has_horarios_grupos1`
    FOREIGN KEY (`grupos_idclave` , `grupos_materias_clave` , `grupos_cicloescolar_periodo` , `grupos_maestros_idcie`)
    REFERENCES `control`.`grupos` (`idclave` , `materias_clave` , `cicloescolar_periodo` , `maestros_idcie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_has_horarios_horarios1`
    FOREIGN KEY (`horarios_idhorario`)
    REFERENCES `control`.`horarios` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
